<?php
/** @var Amasty\AnastasiaModule\Block\Form $block */
/** @var string $cssFormClass */
/** @var string $cssInputClass */
/** @var string $cssSubmitClass */
/** @var string $cssTextClass */

$cssFormClass = $block->hasCssFormClass() ? ' ' . $block->getCssFormClass() : '';
$cssInputClass = $block->hasCssInputClass() ? ' ' . $block->getCssInputClass() : '';
$cssSubmitClass = $block->hasCssSubmitClass() ? ' ' . $block->getCssSubmitClass() : '';
$cssTextClass = $block->hasCssTextClass() ? ' ' . $block->getCssTextClass() : '';
?>

<form name="form_checkout" id="formCheckout" class="<?= $cssFormClass ?>" action="<?php echo $this->getUrl() . 'anastasia/cart/add'; ?>" method="post">
    <label>
        Enter SKU:
        <input type="text" name="sku" class="<?= $cssInputClass ?>"/>
    </label>

    <?php if ($block->isEnabledQty()) { ?>
        <label>
            Enter QTY:
            <input type="number" name="qty" class="<?= $cssInputClass ?>" value="<?= $block->getDefaultQty(); ?>"/>
        </label>
    <?php } ?>

    <div class="<?= $cssTextClass ?>"><?= $block->getChildHtml(); ?></div>
    <input type="submit" value="Отправить" class="<?= $cssSubmitClass ?>"/>
</form>


