<?php
/** @var Amasty\AnastasiaModule\Block\Form $block */
/** @var string $cssFormClass */
/** @var string $cssInputClass */
/** @var string $cssSubmitClass */
/** @var string $cssTextClass */

$cssFormClass = $block->hasCssFormClass() ? ' ' . $block->getCssFormClass() : '';
$cssInputClass = $block->hasCssInputClass() ? ' ' . $block->getCssInputClass() : '';
$cssSubmitClass = $block->hasCssSubmitClass() ? ' ' . $block->getCssSubmitClass() : '';
$cssTextClass = $block->hasCssTextClass() ? ' ' . $block->getCssTextClass() : '';
?>

<form name="form_checkout" id="formCheckout" class="<?= $cssFormClass ?>"
      action="<?= $block->escapeUrl($block->getUrl($block->getFormAction())) ?>"
      method="post"
      data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <label for="sku">Enter SKU:</label>
            <div class="control" data-bind="scope: 'myAutocomplete'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
        </div>

        <div class="field name required">
            <?php if ($block->isEnabledQty()) : ?>
                <label for="qty">Enter QTY:</label>
                <div class="control">
                    <input type="number" name="qty"
                           class="<?= $cssInputClass ?> required-entry validate-greater-than-zero"
                           value="<?= $block->getDefaultQty(); ?>"/>
                </div>
            <?php endif ?>
        </div>
        <div class="<?= $cssTextClass ?>"><?= $block->getChildHtml(); ?></div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="<?= $cssSubmitClass ?> action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>

</form>


<script type="text/x-magento-init">
   {
       "*": {
           "Magento_Ui/js/core/app": {
               "components": {
                   "myAutocomplete": {
                       "component": "Amasty_AnastasiaModule/js/koAutocomplete",
                       "template" : "Amasty_AnastasiaModule/koAutocomplete"
                   }
               }
           }
       }
   }

</script>



